"""add release year

Revision ID: 12833b78962a
Revises: 54a68da0ddf3
Create Date: 2025-08-03 02:32:59.561402

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "12833b78962a"
down_revision: Union[str, Sequence[str], None] = "ce04781f2f30"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("movies", sa.Column("release_year", sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("movies", "release_year")
    # ### end Alembic commands ###
