"""add vote log

Revision ID: 372f2f71ffc7
Revises: decc9ff484e6
Create Date: 2025-08-07 02:16:36.386117

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "372f2f71ffc7"
down_revision: Union[str, Sequence[str], None] = "decc9ff484e6"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "votes_log",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("fingerprint_id", sa.String(), nullable=False),
        sa.Column("source_movie_id", sa.Integer(), nullable=False),
        sa.Column("target_movie_id", sa.Integer(), nullable=False),
        sa.Column(
            "vote_type",
            sa.Enum("DIRECT_LINK", "LLM_AGREEMENT", name="votetype"),
            nullable=False,
        ),
        sa.Column("reference_id", sa.Integer(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.ForeignKeyConstraint(
            ["source_movie_id"],
            ["movies.id"],
        ),
        sa.ForeignKeyConstraint(
            ["target_movie_id"],
            ["movies.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_votes_log_fingerprint_id"),
        "votes_log",
        ["fingerprint_id"],
        unique=False,
    )
    op.create_index(op.f("ix_votes_log_id"), "votes_log", ["id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_votes_log_id"), table_name="votes_log")
    op.drop_index(op.f("ix_votes_log_fingerprint_id"), table_name="votes_log")
    op.drop_table("votes_log")
    # ### end Alembic commands ###
