"""add_request_logs_table

Revision ID: 58ff62b8f380
Revises: 372f2f71ffc7
Create Date: 2025-10-01 00:04:03.107374

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "58ff62b8f380"
down_revision: Union[str, Sequence[str], None] = "372f2f71ffc7"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "request_logs",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column(
            "method",
            sa.Enum(
                "GET",
                "POST",
                "PUT",
                "PATCH",
                "DELETE",
                "HEAD",
                "OPTIONS",
                name="requestmethod",
            ),
            nullable=False,
        ),
        sa.Column("path", sa.String(length=512), nullable=False),
        sa.Column(
            "query_params", postgresql.JSONB(astext_type=sa.Text()), nullable=True
        ),
        sa.Column("client_ip", postgresql.INET(), nullable=True),
        sa.Column("user_agent", sa.Text(), nullable=True),
        sa.Column("referer", sa.String(length=512), nullable=True),
        sa.Column("headers", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("status_code", sa.Integer(), nullable=False),
        sa.Column("response_size", sa.Integer(), nullable=True),
        sa.Column("processing_time", sa.Float(), nullable=True),
        sa.Column("timestamp", sa.DateTime(timezone=True), nullable=False),
        sa.Column("user_id", sa.String(length=64), nullable=True),
        sa.Column("session_id", sa.String(length=128), nullable=True),
        sa.Column("request_size", sa.Integer(), nullable=True),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_request_logs_client_ip"), "request_logs", ["client_ip"], unique=False
    )
    op.create_index(op.f("ix_request_logs_id"), "request_logs", ["id"], unique=False)
    op.create_index(
        op.f("ix_request_logs_method"), "request_logs", ["method"], unique=False
    )
    op.create_index(
        op.f("ix_request_logs_path"), "request_logs", ["path"], unique=False
    )
    op.create_index(
        op.f("ix_request_logs_session_id"), "request_logs", ["session_id"], unique=False
    )
    op.create_index(
        op.f("ix_request_logs_status_code"),
        "request_logs",
        ["status_code"],
        unique=False,
    )
    op.create_index(
        op.f("ix_request_logs_timestamp"), "request_logs", ["timestamp"], unique=False
    )
    op.create_index(
        op.f("ix_request_logs_user_id"), "request_logs", ["user_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_request_logs_user_id"), table_name="request_logs")
    op.drop_index(op.f("ix_request_logs_timestamp"), table_name="request_logs")
    op.drop_index(op.f("ix_request_logs_status_code"), table_name="request_logs")
    op.drop_index(op.f("ix_request_logs_session_id"), table_name="request_logs")
    op.drop_index(op.f("ix_request_logs_path"), table_name="request_logs")
    op.drop_index(op.f("ix_request_logs_method"), table_name="request_logs")
    op.drop_index(op.f("ix_request_logs_id"), table_name="request_logs")
    op.drop_index(op.f("ix_request_logs_client_ip"), table_name="request_logs")
    op.drop_table("request_logs")
    # ### end Alembic commands ###
