"""add processing queue

Revision ID: 87616f7d1a60
Revises: bde0fe71303a
Create Date: 2025-08-04 21:30:26.376111

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "87616f7d1a60"
down_revision: Union[str, Sequence[str], None] = "bde0fe71303a"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "processing_queue",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("source_movie_id", sa.Integer(), nullable=True),
        sa.Column("title", sa.String(), nullable=True),
        sa.Column("release_year", sa.Integer(), nullable=True),
        sa.Column("properties", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column(
            "trigger_source",
            sa.Enum("MANUAL", "RECOMMENDATION", "TRENDING", name="triggersource"),
            nullable=True,
        ),
        sa.Column(
            "status",
            sa.Enum(
                "PENDING", "FAILED", "COMPLETED", "PROCESSING", name="processingstatus"
            ),
            nullable=False,
        ),
        sa.Column("failure_reason", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_processing_queue_id"), "processing_queue", ["id"], unique=False
    )
    op.create_index(
        op.f("ix_processing_queue_status"), "processing_queue", ["status"], unique=False
    )
    op.create_index(
        op.f("ix_processing_queue_title"), "processing_queue", ["title"], unique=False
    )
    op.create_index(
        op.f("ix_processing_queue_trigger_source"),
        "processing_queue",
        ["trigger_source"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_processing_queue_trigger_source"), table_name="processing_queue"
    )
    op.drop_index(op.f("ix_processing_queue_title"), table_name="processing_queue")
    op.drop_index(op.f("ix_processing_queue_status"), table_name="processing_queue")
    op.drop_index(op.f("ix_processing_queue_id"), table_name="processing_queue")
    op.drop_table("processing_queue")
    op.execute("DROP TYPE triggersource;")
    op.execute("DROP TYPE processingstatus;")
    # ### end Alembic commands ###
