"""add llm recommendations

Revision ID: bde0fe71303a
Revises: 12833b78962a
Create Date: 2025-08-03 14:55:12.870605

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bde0fe71303a'
down_revision: Union[str, Sequence[str], None] = '12833b78962a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('llm_recommendations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source_movie_id', sa.Integer(), nullable=False),
    sa.Column('trigger_keywords_hash', sa.String(), nullable=False),
    sa.Column('recommended_movie_id', sa.Integer(), nullable=False),
    sa.Column('llm_justification', sa.JSON(), nullable=False),
    sa.Column('llm_score', sa.Float(), nullable=True),
    sa.Column('user_votes', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['recommended_movie_id'], ['movies.id'], ),
    sa.ForeignKeyConstraint(['source_movie_id'], ['movies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_llm_recommendations_id'), 'llm_recommendations', ['id'], unique=False)
    op.create_index(op.f('ix_llm_recommendations_trigger_keywords_hash'), 'llm_recommendations', ['trigger_keywords_hash'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_llm_recommendations_trigger_keywords_hash'), table_name='llm_recommendations')
    op.drop_index(op.f('ix_llm_recommendations_id'), table_name='llm_recommendations')
    op.drop_table('llm_recommendations')
    # ### end Alembic commands ###
