"""added ai_keywords in movies

Revision ID: ce04781f2f30
Revises: fb0279006192
Create Date: 2025-08-02 14:58:31.251034

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ce04781f2f30'
down_revision: Union[str, Sequence[str], None] = 'fb0279006192'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('movies', sa.Column('ai_keywords', sa.JSON(), nullable=True))
    op.drop_index(op.f('idx_movie_title_fts'), table_name='movies', postgresql_using='gin')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('idx_movie_title_fts'), 'movies', [sa.literal_column("to_tsvector('english'::regconfig, title::text)")], unique=False, postgresql_using='gin')
    op.drop_column('movies', 'ai_keywords')
    # ### end Alembic commands ###
