"""add columns in movies

Revision ID: decc9ff484e6
Revises: 5829dbb445f3
Create Date: 2025-08-06 16:30:11.737973

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "decc9ff484e6"
down_revision: Union[str, Sequence[str], None] = "5829dbb445f3"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("movies", sa.Column("origin_country", sa.JSON(), nullable=True))
    op.add_column("movies", sa.Column("original_language", sa.String(), nullable=True))
    op.add_column("movies", sa.Column("original_title", sa.String(), nullable=True))
    op.add_column("movies", sa.Column("runtime", sa.Integer(), nullable=True))
    op.add_column("movies", sa.Column("tagline", sa.String(), nullable=True))
    op.create_index(
        op.f("ix_movies_embedding"),
        "movies",
        ["embedding"],
        unique=False,
        postgresql_using="hnsw",
        postgresql_ops={"embedding": "vector_cosine_ops"},
    )

    # ### end Alembic commands ###


def downgrade() -> None:
    op.drop_index(
        op.f("ix_movies_embedding"), table_name="movies", postgresql_using="hnsw"
    )
    op.drop_column("movies", "tagline")
    op.drop_column("movies", "runtime")
    op.drop_column("movies", "original_title")
    op.drop_column("movies", "original_language")
    op.drop_column("movies", "origin_country")
    # ### end Alembic commands ###
